package inventory.domain.entity.enums;

public enum TransactionType {
    RECEIPT, PUTAWAY, MOVE, ALLOCATE, DEALLOCATE, PICK, SHIP,
    ADJUSTMENT_INCREASE, ADJUSTMENT_DECREASE,
    RETURN_RECEIPT, SCRAP, TRANSFER_IN, TRANSFER_OUT, HOLD, RELEASE_HOLD
}